(() => {
  'use strict';
  const KEY = 'chemstrike-blue-story-v1';
  const topic = 'Topic XII · Patterns in the Chemical World';
  const scenes = [
    {title:'A label has vanished.',text:'Dr Lin has found an unlabelled, pale blue solution in the school laboratory. The logbook is incomplete. Your task: identify the metal ion and explain the evidence. The bottle stays sealed until you choose a safe test.',question:'Where should the investigation begin?',options:['Inspect the sample and open a virtual test aliquot.'],answer:0,hint:'A small, separate sample lets you test without contaminating the original.',explain:'Sample A logged: pale blue solution. Its colour is a clue, not proof.',evidence:'Observation: Sample A is a pale blue solution. Identity is not yet confirmed.'},
    {title:'Choose your first lead.',text:'Two reagents are available. One can provide a second, distinctive observation when added in excess. Use a fresh aliquot for each test.',question:'Which reagent will you use for the two-stage investigation?',options:['Aqueous ammonia, added dropwise.','Aqueous sodium hydroxide, then more of it.','Water, added dropwise.'],answer:0,hint:'Choose a reagent that can act first as a base, and then as a ligand.',explain:'A few drops of aqueous ammonia have been added. Examine the observation feed before moving on.',reveal:1},
    {title:'Something appears in the liquid.',text:'“Record exactly what you can see,” says Dr Lin. “Do not replace an observation with the name of a substance.”',question:'Which entry belongs in the observation log?',options:['A deep blue gas escapes.','A light-blue precipitate forms.','The solution turns into copper metal.'],answer:1,hint:'A precipitate is an insoluble solid appearing in a liquid.',explain:'The light-blue precipitate is copper(II) hydroxide. Formation of the solid is precipitation, not reduction to copper metal.',evidence:'Observation: a little aqueous ammonia produces a light-blue precipitate.'},
    {title:'The first role of ammonia.',text:'A second investigator claims the solid forms because ammonia donates electrons to reduce the metal. Dr Lin asks you to check that explanation.',question:'Why does a small amount of ammonia cause precipitation?',options:['Ammonia supplies electrons, reducing Cu²⁺ to Cu.','Ammonia produces OH⁻ in water; Cu(OH)₂ precipitates.','Ammonia removes every water molecule by evaporation.'],answer:1,hint:'NH₃ + H₂O ⇌ NH₄⁺ + OH⁻. What can OH⁻ do with Cu²⁺?',explain:'NH₃ + H₂O ⇌ NH₄⁺ + OH⁻\nCu²⁺(aq) + 2OH⁻(aq) → Cu(OH)₂(s)\nCopper stays in oxidation state +2. Ammonia is acting as a base.',evidence:'Explanation: OH⁻ generated by ammonia precipitates Cu(OH)₂. No redox change occurs.'},
    {title:'Follow the second clue.',text:'The precipitate has not solved the whole case. Dr Lin points to the reagent label: “Observe the effect of excess reagent.”',question:'What should you do next in this virtual test?',options:['Filter immediately and discard the liquid.','Add more aqueous ammonia until it is in excess.','Add water and call the colour change a positive test.'],answer:1,hint:'Use excess of the same ligand-forming reagent, not just more solvent.',explain:'The precipitate dissolves in excess ammonia, leaving a deep blue solution. Scrub the reaction timeline to compare all three stages.',reveal:2,evidence:'Observation: the precipitate dissolves in excess ammonia to give a deep blue solution.'},
    {title:'Inside the deep blue solution.',text:'Your evidence now points to copper(II). The particle viewer is unlocked. Rotate the coordination model: four equatorial sites and two longer axial sites surround the metal.',question:'Which ligand arrangement represents the deep blue complex?',options:['Six NH₃ ligands: [Cu(NH₃)₆]²⁺.','Four NH₃ and two H₂O ligands: [Cu(NH₃)₄(H₂O)₂]²⁺.','Four NH₄⁺ and two OH⁻ ligands.'],answer:1,hint:'Four ammonia molecules replace four water ligands. Two water ligands remain.',explain:'Net ligand-exchange representation:\n[Cu(H₂O)₆]²⁺ + 4NH₃ ⇌ [Cu(NH₃)₄(H₂O)₂]²⁺ + 4H₂O\nThe new coordination environment changes the colour; Cu remains +2.',evidence:'Particle explanation: four NH₃ ligands and two H₂O ligands coordinate to Cu²⁺ in the deep blue complex.'},
    {title:'Trace the donated pair.',text:'“The bond is covalent,” Dr Lin explains, “but both electrons in the shared pair originally come from one partner.” Inspect the donor arrow in the model.',question:'In the N → Cu dative covalent bond, who provides the pair?',options:['Cu²⁺ donates two electrons to nitrogen.','Nitrogen and copper each supply one electron.','Nitrogen in NH₃ donates its lone pair to Cu²⁺.'],answer:2,hint:'A ligand is an electron-pair donor. Locate nitrogen’s lone pair.',explain:'NH₃ donates a lone pair on N to the metal centre. Water ligands donate from O. A donor arrow is bookkeeping for bond formation, not a continuing current of electrons.',evidence:'Bonding explanation: NH₃ donates the nitrogen lone pair to Cu²⁺; water coordinates through O.'},
    {title:'Close the case.',text:'The missing label listed a metal ion, not the full salt. The counter-ion was never tested. Choose a conclusion supported by the evidence you actually collected.',question:'Which report should be filed?',options:['Cu²⁺ is supported by the precipitate and deep blue solution in excess ammonia; the counter-ion remains unknown.','The sample must be copper(II) sulfate because every blue solution contains sulfate.','The sample contains Cu⁺ because the colour became darker.'],answer:0,hint:'Combine both observations. Do not identify a counter-ion without a separate test.',explain:'Case solved: the observations support copper(II) ions. The colour change is associated with complex formation, not a change in oxidation state.',evidence:'Conclusion: evidence supports Cu²⁺. The anion and full salt identity have not been established.'}
  ];
  const fresh = () => ({version:1,id:'blue-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),step:0,solved:[],wrong:[],hints:[],evidence:[],maxPhase:0,finished:false,started:Date.now()});
  let storageOK = true, state;
  try {const value=JSON.parse(localStorage.getItem(KEY));state=value&&value.version===1&&Number.isInteger(value.step)&&value.step>=0&&value.step<8&&['solved','wrong','hints','evidence'].every(k=>Array.isArray(value[k]))?value:fresh();} catch (_) {state=fresh();storageOK=false;}
  const $ = id => document.getElementById(id);
  let phase=state.maxPhase, playing=false, view='lab', branch=false, yaw=25, pitch=20, last=0;
  const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const score=()=>state.solved.filter(i=>i>0&&!state.wrong.includes(i)&&!state.hints.includes(i)).length;
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){storageOK=false;}if(!storageOK)$('saveStatus').textContent='Saving is unavailable in this browser. You can play, but progress may be lost when you leave.';}
  function evidence(){const list=$('evidence');list.replaceChildren();if(!state.evidence.length){const li=document.createElement('li');li.textContent='No tests yet. Inspect the sealed sample first.';list.append(li);}state.evidence.forEach(text=>{const li=document.createElement('li');li.textContent=text;list.append(li);});}
  function feedback(text,kind){$('feedback').textContent=text;$('feedback').className='feedback '+kind;}
  function recordWrong(chosen){
    const api=window.ChemistryTools;if(!api)return;
    try{const list=api.mistakes(),id='blue-mystery-scene-'+state.step,old=list.find(x=>x.id===id),now=new Date().toISOString();
      const record={id,topic,number:state.step+1,question:scenes[state.step].question,source:'Blue Solution Mystery · scene '+(state.step+1),reason:'Wrong game answer',selected:{letter:'',text:chosen},href:'blue-mystery.html',mastered:false,attempts:(old?.attempts||0)+1,savedAt:old?.savedAt||now,lastTried:now};
      if(old)Object.assign(old,record);else list.unshift(record);api.writeMistakes(list);
    }catch(_){storageOK=false;save();}
  }
  function choose(index){
    const s=scenes[state.step];if(state.finished||state.solved.includes(state.step))return;
    if(index!==s.answer){
      if(!state.wrong.includes(state.step)){state.wrong.push(state.step);recordWrong(s.options[index]);}save();
      if(state.step===1&&index===1){branch=true;playing=false;draw();feedback('SIDE TEST · NaOH forms a light-blue Cu(OH)₂ precipitate that does not dissolve in excess NaOH under these test conditions. Useful, but it does not give the deep blue ammonia complex. Select aqueous ammonia to test a fresh aliquot.','hint');}
      else feedback('Recheck the evidence. '+s.hint+' You may try again; this step no longer earns an independent-recall point.','bad');
      const b=$('choices').children[index];b.classList.add('wrong');return;
    }
    branch=false;state.solved.push(state.step);if(s.evidence&&!state.evidence.includes(s.evidence))state.evidence.push(s.evidence);
    if(s.reveal){phase=state.maxPhase;state.maxPhase=s.reveal;if(reduced)phase=s.reveal;else playing=true;}
    save();render();feedback(s.explain,'good');
  }
  function render(){
    if(state.finished){showResult();return;}
    const s=scenes[state.step],done=state.solved.includes(state.step);
    $('sceneTitle').textContent=s.title;$('narration').textContent=s.text;$('question').textContent=s.question;
    $('sceneCount').textContent='Scene '+(state.step+1)+' of 8';$('caseProgress').value=state.solved.length;$('score').textContent='Independent recall '+score()+' / 7';
    $('choices').replaceChildren();s.options.forEach((label,i)=>{const b=document.createElement('button'),key=document.createElement('span');key.textContent=String.fromCharCode(65+i);b.append(key,document.createTextNode(label));b.disabled=done;if(done&&i===s.answer)b.className='correct';b.onclick=()=>choose(i);$('choices').append(b);});
    $('hint').hidden=done;$('continue').hidden=!done;$('continue').textContent=state.step===7?'File the case report →':'Continue →';feedback(done?s.explain:'','');
    $('time').max=state.maxPhase;$('modelView').disabled=state.step<5;$('modelView').title=state.step<5?'Unlock by collecting both reagent observations':'';
    $('play').disabled=state.maxPhase===0;$('replay').disabled=state.maxPhase===0;evidence();draw();
  }
  function next(){
    if(!state.solved.includes(state.step)||state.finished)return;
    playing=false;phase=state.maxPhase;
    if(state.step===7){state.finished=true;save();showResult();return;}
    state.step++;save();render();$('sceneTitle').focus();
  }
  function completeProgress(){
    const api=window.ChemistryTools;if(!api){$('saveStatus').textContent='Case saved locally. Hub progress tools are unavailable; reload later to sync this attempt.';return;}
    try {
      const data=api.progress();if(!data.history.some(x=>x.relatedId===state.id))api.logSession({type:'game',topic,key:'blue-mystery',label:'The Blue Solution Mystery',score:score(),total:7,xp:0,relatedId:state.id,minutes:Math.max(1,Math.round((Date.now()-state.started)/60000))});
      const p=api.profile();p.storyAwards=p.storyAwards||{};
      if(!p.storyAwards[state.id]){const xp=20+score()*5;p.xp=(p.xp||0)+xp;p.played=(p.played||0)+1;p.storyAwards[state.id]=xp;api.writeProfile(p);}
      $('saveStatus').textContent='Case and independent-recall score saved in this browser’s Hub progress. No teacher account or cloud sync is used.';
    } catch(_){storageOK=false;save();}
  }
  function showResult(){
    playing=false;phase=2;state.maxPhase=2;view='lab';$('rotation').hidden=true;
    $('sceneTitle').textContent='Case closed. Evidence secured.';$('narration').textContent=score()>=6?'Your report is well supported. Return another day to check what you can recall without hints.':'You solved the case with support. Revisit the steps where you used a hint or made an error, then try a fresh attempt.';
    $('question').textContent='Finding: copper(II) ions supported; counter-ion unknown.';$('choices').replaceChildren();$('hint').hidden=true;$('continue').hidden=true;feedback('','');
    $('sceneCount').textContent='Case complete';$('caseProgress').value=8;$('score').textContent='Independent recall '+score()+' / 7';
    $('result').hidden=false;$('result').replaceChildren();
    const strong=document.createElement('strong');strong.textContent=score()+' / 7 independent checks';
    const p=document.createElement('p');const review=[...new Set(state.wrong.concat(state.hints))].filter(i=>i>0);p.textContent='+'+(20+score()*5)+' XP · '+(review.length?'Review: '+review.map(i=>scenes[i].title).join(' '):'All seven checks completed correctly without hints.');
    $('result').append(strong,p);[['mistakes.html','Open Mistake Coach'],['ligand-exchange.html','Explore the full 3D lab'],['games.html','Back to Arcade']].forEach(([href,text])=>{const a=document.createElement('a');a.href=href;a.textContent=text;$('result').append(a);});
    $('time').max=2;$('modelView').disabled=false;$('play').disabled=false;$('replay').disabled=false;evidence();completeProgress();draw();
  }
  const canvas=$('visual'),ctx=canvas.getContext('2d');
  function text(label,x,y,size=22,colour='#dcecf2'){ctx.fillStyle=colour;ctx.font='500 '+size+'px system-ui';ctx.textAlign='center';ctx.fillText(label,x,y);}
  function circle(x,y,r,colour){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=colour;ctx.fill();}
  function sphere(x,y,r,colour){const g=ctx.createRadialGradient(x-r*.35,y-r*.4,1,x,y,r);g.addColorStop(0,'#fff');g.addColorStop(.26,colour);g.addColorStop(1,'#18394c');circle(x,y,r,g);}
  function precipitateAmount(){return branch?1:phase<=1?phase:2-phase;}
  function lab(){
    const p=branch?1:phase,cloud=precipitateAmount();
    ctx.save();ctx.beginPath();ctx.moveTo(315,100);ctx.lineTo(315,452);ctx.quadraticCurveTo(315,480,345,480);ctx.lineTo(555,480);ctx.quadraticCurveTo(585,480,585,452);ctx.lineTo(585,100);ctx.closePath();ctx.clip();
    const blue=p>1?Math.round(155-(p-1)*100):155;ctx.fillStyle='rgba(35,'+blue+',245,'+(p>1?.35+(p-1)*.5:.32)+')';ctx.fillRect(315,230,270,260);
    ctx.fillStyle='#a6dffa33';ctx.beginPath();ctx.ellipse(450,230,135,11,0,0,Math.PI*2);ctx.fill();
    for(let i=0;i<85;i++){const x=328+(i*79%240),fall=(i*17%180),y=430-(1-Math.min(1,cloud))*fall+(i%6)*6;ctx.globalAlpha=Math.max(0,cloud)*(.35+(i%4)*.14);circle(x,y,5+(i%7),'#85d5f6');}ctx.globalAlpha=1;
    ctx.fillStyle='#e9faff0f';ctx.fillRect(325,115,14,340);ctx.restore();
    ctx.strokeStyle='#b2d7e1';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(315,100);ctx.lineTo(315,452);ctx.quadraticCurveTo(315,480,345,480);ctx.lineTo(555,480);ctx.quadraticCurveTo(585,480,585,452);ctx.lineTo(585,100);ctx.stroke();ctx.beginPath();ctx.moveTo(300,100);ctx.lineTo(600,100);ctx.stroke();
    const label=branch?'SIDE ALIQUOT · NaOH':p<.02?'SAMPLE A · NO REAGENT':p<=1?'A LITTLE AQUEOUS AMMONIA':'EXCESS AQUEOUS AMMONIA';text(label,450,65,19,'#72edcd');
    if(playing){const y=120+((p*550)%90);circle(450,y,6,'#c8f5fb');}
    text(branch?'Precipitate remains in excess NaOH':p<.03?'Pale blue solution':p<1.05?'Light-blue precipitate forming':'Precipitate dissolves → deep blue solution',450,540,22);
  }
  function project(v){const a=yaw*Math.PI/180,b=pitch*Math.PI/180,x=v[0]*Math.cos(a)+v[2]*Math.sin(a),z=-v[0]*Math.sin(a)+v[2]*Math.cos(a),y=v[1]*Math.cos(b)-z*Math.sin(b),depth=v[1]*Math.sin(b)+z*Math.cos(b),scale=650/(650+depth);return{x:450+x*scale,y:300+y*scale,z:depth,scale};}
  function model(){
    if(phase>.35&&phase<1.55){text('Cu(OH)₂(s) · EXTENDED SOLID',450,100,23,'#72edcd');text('No isolated molecular model shown.',450,275,27);text('The precipitate is a solid structure,',450,325,23);text('not a collection of separate six-ligand molecules.',450,363,23);return;}
    const ammonia=phase>=1.55;const positions=[[160,0,0],[-160,0,0],[0,0,160],[0,0,-160],[0,-215,0],[0,215,0]];
    const nodes=positions.map((v,i)=>({...project(v),i,label:ammonia&&i<4?'NH₃':'H₂O',colour:ammonia&&i<4?'#88acf9':'#fc9c88'}));
    const centre=project([0,0,0]);ctx.lineWidth=8;
    nodes.filter(n=>n.z>0).sort((a,b)=>b.z-a.z).forEach(n=>bond(n));
    nodes.filter(n=>n.z>0).sort((a,b)=>b.z-a.z).forEach(n=>node(n));
    sphere(450,300,42,'#ffd68b');text('Cu²⁺',450,309,25,'#092332');
    nodes.filter(n=>n.z<=0).sort((a,b)=>b.z-a.z).forEach(n=>{bond(n);node(n);});
    function bond(n){ctx.strokeStyle=n.i>3?'#658497':'#94bacd';ctx.lineWidth=n.i>3?4:7;ctx.beginPath();ctx.moveTo(centre.x,centre.y);ctx.lineTo(n.x,n.y);ctx.stroke();}
    function node(n){sphere(n.x,n.y,29*n.scale,n.colour);text(n.label,n.x,n.y+6,Math.round(19*n.scale),'#061923');}
    text(ammonia?'[Cu(NH₃)₄(H₂O)₂]²⁺':'[Cu(H₂O)₆]²⁺',450,60,28,'#72edcd');
    text('Six donor groups · elongated octahedral schematic',450,555,19);
    if(ammonia){ctx.fillStyle='#72edcd';ctx.fillRect(615,92,240,86);text('N: → Cu²⁺',735,126,24,'#092332');text('Lone pair donor → acceptor',735,155,16,'#092332');}
  }
  function draw(){
    if(!ctx)return;ctx.clearRect(0,0,900,600);ctx.fillStyle='#091f2c';ctx.fillRect(0,0,900,600);ctx.strokeStyle='#15323f';ctx.lineWidth=1;for(let x=30;x<900;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,600);ctx.stroke();}for(let y=15;y<600;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(900,y);ctx.stroke();}
    if(view==='lab')lab();else model();
    const cap=branch?'Side test: Cu(OH)₂ remains in excess NaOH. Return to a fresh sample for ammonia.':phase<.05?'Pale blue solution; colour alone is not proof.':phase<1.05?'A little ammonia produces a light-blue precipitate.':phase<1.95?'Excess ammonia dissolves the precipitate; the solution becomes deep blue.':'Deep blue solution: [Cu(NH₃)₄(H₂O)₂]²⁺.';
    $('visualCaption').textContent=cap;canvas.setAttribute('aria-label',view==='lab'?cap:'Rotatable coordination schematic. '+cap);
    $('time').value=phase;$('timeLabel').textContent=phase<.05?'Initial sample':phase<=1?'A little ammonia':'Excess ammonia';$('play').textContent=playing?'Pause':'Play';
    $('viewHeading').textContent=view==='lab'?'OBSERVATION FEED':'PARTICLE EXPLANATION';$('labView').setAttribute('aria-pressed',String(view==='lab'));$('modelView').setAttribute('aria-pressed',String(view==='model'));
  }
  function tick(now){if(playing&&!document.hidden){phase=Math.min(state.maxPhase,phase+Math.min(now-last,60)/4000);if(phase>=state.maxPhase)playing=false;draw();}last=now;requestAnimationFrame(tick);}
  $('hint').onclick=()=>{if(!state.hints.includes(state.step))state.hints.push(state.step);save();feedback(scenes[state.step].hint+' This step counts as supported recall.','hint');};
  $('continue').onclick=next;
  $('time').oninput=e=>{branch=false;playing=false;phase=+e.target.value;draw();};
  $('play').onclick=()=>{branch=false;if(phase>=state.maxPhase)phase=0;playing=!playing;draw();};
  $('replay').onclick=()=>{branch=false;phase=0;playing=!reduced;draw();};
  function setView(mode){if(mode==='model'&&state.step<5)return;view=mode;$('rotation').hidden=mode!=='model';$('modelNote').textContent=mode==='model'?'Each sphere represents a donor group, not an atom-sized molecule. Rotate with the sliders or left/right arrow keys. Geometry and bond lengths are schematic.':'Schematic laboratory observation, not a video. Reaction progress is illustrative, not to scale.';draw();}
  $('labView').onclick=()=>setView('lab');$('modelView').onclick=()=>setView('model');
  $('angle').oninput=e=>{yaw=+e.target.value;draw();};$('tilt').oninput=e=>{pitch=+e.target.value;draw();};
  canvas.onkeydown=e=>{if(view==='model'&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();yaw=Math.max(-180,Math.min(180,yaw+(e.key==='ArrowLeft'?-5:5)));$('angle').value=yaw;draw();}};
  $('restart').onclick=()=>{if(!confirm('Start a new case? The current story position will restart. Existing Hub scores and mistakes will be kept.'))return;state=fresh();phase=0;playing=false;branch=false;view='lab';$('result').hidden=true;$('rotation').hidden=true;save();render();};
  save();render();requestAnimationFrame(tick);
})();
