(function(){
'use strict';
const data=window.CommonSetupData,rooms={all:'All set-ups',earth:'Planet Earth',tests:'Tests & ions',metals:'Metals',acid:'Acids & salts',redox:'Cells & electrolysis',physical:'Energy & rate',organic:'Organic',analysis:'Analytical'},$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let active=0,room='all',panel='how',labels=true,motion=false,done={};try{done=JSON.parse(localStorage.getItem('chem-common-setups-v1')||'{}')||{}}catch(e){}
function apparatus(s){const ref=s.figure;return `<figure class="source-figure"><div class="figure-scroll"><img class="source-apparatus" src="${ref.file}" width="${ref.width}" height="${ref.height}" alt="${esc(s.title)}: apparatus diagram from source page ${ref.page}"></div><figcaption>Source apparatus · PDF page ${ref.page} · <a href="${ref.file}" target="_blank" rel="noopener">Open full-size diagram ↗</a></figcaption></figure><p class="recall-cover" hidden>Sketch the set-up from memory. Include the glassware, connections and safety details, then reveal the diagram to check.</p><div class="part-buttons" aria-label="Apparatus functions">${s.parts.map((p,i)=>`<button type="button" class="marker" data-part="${i}">${i+1} · ${esc(p[0])}</button>`).join('')}</div>`}
function imageState(){const f=document.querySelector('.source-figure'),cover=document.querySelector('.recall-cover');if(f)f.hidden=!labels;if(cover)cover.hidden=labels;$('labels').textContent=labels?'Hide diagram to recall':'Reveal diagram';$('labels').setAttribute('aria-pressed',!labels);$('apparatus').classList.toggle('zoomed',motion);$('animate').textContent=motion?'Fit diagram':'Enlarge diagram';$('animate').setAttribute('aria-pressed',motion);$('animate').disabled=!labels;}
function count(){const n=Object.values(done).filter(Boolean).length;$('masteredCount').textContent=n+' / '+data.length;$('masteryBar').style.width=100*n/data.length+'%'}
function tabs(){$('roomTabs').innerHTML=Object.entries(rooms).map(([k,v])=>`<button type="button" role="tab" data-room="${k}" aria-selected="${k===room}">${v}</button>`).join('');document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{room=b.dataset.room;tabs();grid()})}
function shown(){const q=$('search').value.trim().toLowerCase();return data.map((s,i)=>({s,i})).filter(x=>(room==='all'||x.s.room===room)&&(!q||(x.s.title+' '+x.s.subtitle+' '+x.s.topic).toLowerCase().includes(q)))}
function grid(){const a=shown();$('stationGrid').innerHTML=a.map(({s,i})=>`<button class="station ${i===active?'selected':''}" data-index="${i}" type="button"><small>${esc(s.topic)}</small><b>${esc(s.title)}</b><span>${esc(s.subtitle)}</span>${done[i]?'<i class="tick">✓</i>':''}</button>`).join('');$('empty').hidden=!!a.length;document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>select(+b.dataset.index,true))}
function info(){const s=data[active];$('conceptContent').innerHTML=panel==='how'?`<h3>Build and use</h3><ol>${s.steps.map(x=>'<li>'+esc(x)+'</li>').join('')}</ol><h3>Key relationship</h3><p class="equation">${esc(s.equation)}</p>`:panel==='observe'?`<h3>What you should see or measure</h3><ul>${s.observe.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul><h3>Answer pattern</h3><p>State the visible or measured change, then name the species or process responsible.</p>`:`<h3>Common mark-losing errors</h3><ul>${s.traps.map(x=>'<li class="trap">'+esc(x)+'</li>').join('')}</ul><h3>Action + purpose</h3><p>${esc(s.steps[0])}</p>`;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel))}
function challenge(){const s=data[active];$('challengePrompt').textContent='A student is setting up '+s.title.toLowerCase()+'. Which action is correct?';$('challengeOptions').innerHTML=s.quiz.map((q,i)=>`<button type="button" data-choice="${i}">${String.fromCharCode(65+i)} · ${esc(q)}</button>`).join('');$('challengeFeedback').textContent='';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.choice===s.correct;document.querySelectorAll('[data-choice]').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');if(!ok)document.querySelector(`[data-choice="${s.correct}"]`).classList.add('correct');$('challengeFeedback').textContent=ok?'Correct. That protects the validity and safety of the set-up.':'Review the key answer: '+s.answer})}
function select(i,scroll=false){active=(i+data.length)%data.length;panel='how';const s=data[active];$('stationTopic').textContent=s.topic;$('stationTitle').textContent=s.title;$('stationPurpose').textContent=s.purpose;$('stationNumber').textContent=String(active+1).padStart(2,'0')+' / '+data.length;$('keyAnswer').textContent=s.answer;$('apparatus').innerHTML=apparatus(s);imageState();$('mastered').textContent=done[active]?'✓ Checked':'Mark as checked';$('mastered').classList.toggle('done',!!done[active]);$('componentDetail').textContent='Choose an apparatus part below the diagram to see its function.';document.querySelectorAll('.marker').forEach(m=>{const show=()=>{const p=s.parts[+m.dataset.part];$('componentDetail').innerHTML='<b>'+esc(p[0])+':</b> '+esc(p[1])};m.onclick=show;m.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}}});info();challenge();grid();const slug=s.title.toLowerCase().replace(/[^a-z0-9]+/g,'-');history.replaceState(null,'','#setup='+slug);if(scroll)$('lab').scrollIntoView({behavior:'smooth',block:'start'})}
$('search').oninput=grid;$('previous').onclick=()=>select(active-1);$('next').onclick=()=>select(active+1);$('randomSetup').onclick=()=>select(Math.floor(Math.random()*data.length),true);$('labels').onclick=()=>{labels=!labels;imageState()};$('animate').onclick=()=>{motion=!motion;imageState()};$('mastered').onclick=()=>{done[active]=!done[active];localStorage.setItem('chem-common-setups-v1',JSON.stringify(done));count();grid();$('mastered').textContent=done[active]?'✓ Checked':'Mark as checked';$('mastered').classList.toggle('done',!!done[active])};document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{panel=b.dataset.panel;info()});
const hash=(location.hash.match(/^#setup=(.+)$/)||[])[1];if(hash){const i=data.findIndex(s=>s.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')===decodeURIComponent(hash));if(i>=0)active=i}tabs();grid();select(active);count();
})();
