'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let language='zh-Hant'; const T=(zh,en)=>language==='en'?en:zh; const banks=new Map();
let bank, section='A1', chosenTopics=new Set(), selected=new Set(), page=0, busy=false, showSelected=false;
const assetCache=new Map();const stateKey='dse-topic-bank-v1';
const options=()=>({title:$('bookletTitle').value.trim()||'數學課題練習',className:$('className').value.trim(),duration:$('duration').value,mode:$('mode').value,sort:$('sort').value,extraSpace:$('extraSpace').checked,language});
const yearMatch=q=>q.year>=+$('yearFrom').value&&q.year<=+$('yearTo').value;
const inTopics=()=>bank.questions.filter(q=>chosenTopics.has(q.topic)&&yearMatch(q));
const chosen=()=>bank.questions.filter(q=>selected.has(q.id));
function persist(){try{localStorage.setItem(stateKey,JSON.stringify({language,selected:[...selected],topics:[...chosenTopics],section,from:$('yearFrom').value,to:$('yearTo').value,options:options()}));}catch{}}
function toast(t){$('toast').textContent=translateText(t);$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',3000);}
function setOptions(o={}){for(const [k,id]of Object.entries({title:'bookletTitle',className:'className',duration:'duration',mode:'mode',sort:'sort'}))if(o[k]!=null&&(!['mode','sort'].includes(k)||({mode:['student','teacher'],sort:['topic','latest','year']}[k].includes(o[k]))))$(id).value=String(o[k]);$('extraSpace').checked=!!o.extraSpace;}
function renderTopics(){document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===section));$('topicList').innerHTML=bank.topics.filter(t=>t.section===section).map(t=>{const n=bank.questions.filter(q=>q.topic===t.id&&yearMatch(q)).length;return `<button class="topic-btn ${chosenTopics.has(t.id)?'selected':''}" data-topic="${esc(t.id)}" aria-pressed="${chosenTopics.has(t.id)}"><span class="tick">${chosenTopics.has(t.id)?'✓':''}</span><span class="name">${esc(t.name)}</span><span class="n">${n}</span></button>`;}).join('');}
function filtered(){let a=showSelected?chosen():inTopics();const query=$('search').value.toLowerCase().trim();if(query)a=a.filter(q=>`${q.section} ${q.topicName} ${q.subtopic} ${q.year} 第 ${q.number} 題`.toLowerCase().includes(query));return BankPDF.ordered(a,bank.topics,$('sort').value);}
function renderList(){const a=filtered();page=Math.max(0,Math.min(page,Math.ceil(a.length/10)-1));$('resultCount').textContent=`${a.length} 題`;$('listLabel').textContent=showSelected?'小冊子內的題目':`${chosenTopics.size} 個已選課題 · ${$('yearFrom').value}–${$('yearTo').value}`;
 $('questionList').innerHTML=a.slice(page*10,page*10+10).map(q=>`<article class="q-card ${selected.has(q.id)?'chosen':''}"><div class="q-main"><input type="checkbox" data-q="${q.id}" ${selected.has(q.id)?'checked':''} aria-label="選取 ${q.year} 年 ${q.section} 第 ${q.number} 題"><div class="q-info"><div class="q-title">${q.year} 年 · 第 ${q.number} 題 ${q.year===2026?'<span class="new">2026</span>':''}</div><p>${esc(q.subtopic||q.topicName)}</p></div><span class="q-marks">${q.marks} 分</span></div><div class="q-bottom"><span class="badge">${q.section}</span><span class="badge">${esc(q.topicName)}</span><button class="text-btn" data-preview="${q.id}">檢視題目 ↗</button></div></article>`).join('')||'<div class="empty">'+(showSelected?'尚未加入題目。':chosenTopics.size?'此範圍沒有符合的題目。<br>試試其他年份或課題。':'請選擇左側課題。<br>按一下即可加入課題內的題目。')+'</div>';
 const pages=Math.ceil(a.length/10);$('pagination').innerHTML=pages>1?`<button data-page="prev" ${page===0?'disabled':''}>← 上一頁</button><span>${page+1} / ${pages}</span><button data-page="next" ${page===pages-1?'disabled':''}>下一頁 →</button>`:'';$('selectVisible').disabled=!a.length;applyI18n();
}
function renderSummary(){const a=chosen(),o=options(),names=[...new Set(a.map(q=>q.topicName))];$('selectedCount').textContent=a.length;$('selectedMarks').textContent=a.reduce((n,q)=>n+q.marks,0);$('estimatedPages').textContent=a.reduce((n,q)=>n+q[o.mode].length+(o.extraSpace?1:0),0);$('previewTitle').textContent=o.title;$('previewTopics').textContent=names.length?names.join(' · '):'選擇課題以建立練習';$('previewYears').textContent=a.length?`${Math.min(...a.map(q=>q.year))}–${Math.max(...a.map(q=>q.year))}`:'2012–2026';$('previewMode').textContent=o.mode==='student'?'學生版':'教師版';$('exportPdf').disabled=!a.length||busy;$('reviewSelection').textContent=showSelected?T('返回課題結果','Back to topic results'):T('查看已選題目','Review selected questions');persist();applyI18n();}
function render(){renderTopics();renderList();renderSummary();applyI18n();}
function modal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').showModal();applyI18n();}
function preview(id){const q=bank.questions.find(q=>q.id===id);modal(`${q.year} 年 · ${q.section} 第 ${q.number} 題`, `<p>${esc(q.topicName)} <span class="badge">${q.marks} 分</span></p><p style="font-size:11px;color:#839185">預覽顯示題目的第一頁；PDF 輸出會包含整題及續頁。</p><img src="${q.thumbnail||`thumbs/${q.id}.jpg`}" alt="${q.year} 年第 ${q.number} 題的原 PDF 題目預覽"><p><a href="${q.student[0].asset}#page=${q.student[0].page+1}" target="_blank" rel="noopener">開啟原題目 PDF ↗</a>　<a href="${q.teacher[0].asset}#page=${q.teacher[0].page+1}" target="_blank" rel="noopener">開啟評卷參考 PDF ↗</a></p>`);}
function coverage(){if(language==='en')return englishCoverage();modal('題庫涵蓋範圍',`<p>已匯入 <b>${bank.questions.length} 題</b>、${bank.topics.length} 個分部課題，涵蓋 2012–2026 年。收錄以現有課題小冊子為準，A2 並非各年份全卷題目。</p><table><thead><tr><th>年份</th><th>A1</th><th>A2</th><th>B</th><th>總題數</th></tr></thead><tbody>${Array.from({length:15},(_,i)=>2026-i).map(y=>{const counts=['A1','A2','B'].map(s=>bank.questions.filter(q=>q.year===y&&q.section===s).length);return `<tr><td>${y}</td>${counts.map(n=>`<td>${n}</td>`).join('')}<td>${counts.reduce((a,b)=>a+b,0)}</td></tr>`;}).join('')}</tbody></table><p style="font-size:11px;color:#839185">2026 年中文題目沿用已轉換的版本；未與中文原卷逐字比較。教師版評卷參考亦沿用現有小冊子。</p>`);}
function download(bytes,name,type='application/pdf'){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function wrap(ctx,text,x,y,width,lineHeight,max=100){let line='',n=0;const parts=language==='en'?String(text).match(/\S+\s*|\s+/g)||[]:[...String(text)];for(const part of parts){if(ctx.measureText(line+part).width>width&&line){ctx.fillText(line.trimEnd(),x,y+n*lineHeight);line='';n++;if(n>=max)return y+n*lineHeight;}line+=part;}if(line){ctx.fillText(line.trimEnd(),x,y+n*lineHeight);n++;}return y+n*lineHeight;}
function renderSheet(kind,data){const header=kind==='header',w=header?525:BankPDF.W,h=header?30:BankPDF.H,scale=3,c=document.createElement('canvas');c.width=Math.ceil(w*scale);c.height=Math.ceil(h*scale);const ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);const font=(size,weight=400)=>{ctx.font=`${weight} ${size}px "Noto Sans TC","PingFang TC","Microsoft JhengHei",sans-serif`;ctx.fillStyle='#223c3c';};
 if(header){ctx.fillStyle='#185e50';ctx.fillRect(0,0,w,h);ctx.fillStyle='white';ctx.font='500 11px "Microsoft JhengHei",sans-serif';ctx.fillText(`${String(data.index).padStart(2,'0')}  |  ${data.q.section} · ${data.q.topicName}`,12,20);ctx.textAlign='right';ctx.font='10px "Microsoft JhengHei",sans-serif';ctx.fillText(data.working?T('作答紙','Working paper'):data.options.mode==='teacher'?T('教師版','Teacher edition'):T('學生版','Student edition'),w-12,20);}
 else if(kind==='cover'){const {rows,options:o}=data;ctx.fillStyle='#f4f5eb';ctx.fillRect(0,0,w,h);ctx.fillStyle='#185e50';ctx.fillRect(40,45,42,5);font(11,500);ctx.fillText('HKDSE MATHEMATICS · PAPER 1',40,80);font(11);ctx.fillStyle='#718771';ctx.fillText(T('香港中學文憑考試數學 · 卷一','Hong Kong Diploma of Secondary Education · Mathematics'),40,104);font(o.title.length>30?28:34,600);let y=wrap(ctx,o.title,40,226,500,48,3);font(14);ctx.fillStyle='#718771';ctx.fillText(o.mode==='teacher'?T('教師版 · 題目及評卷參考','Teacher edition · Questions and marking schemes'):T('學生版 · 課題練習','Student edition · Topic practice'),40,y+25);font(12);const names=[...new Set(rows.map(q=>`${q.section} ${q.topicName}`))];y=wrap(ctx,names.join('  /  '),40,y+80,480,23,8);font(12);ctx.fillText(`${rows.length} ${T('題','questions')}　｜　${rows.reduce((n,q)=>n+q.marks,0)} ${T('分','marks')}　｜　${Math.min(...rows.map(q=>q.year))}–${Math.max(...rows.map(q=>q.year))}`,40,660);if(o.className)ctx.fillText(`${T('班別：','Class: ')}${o.className}`,40,690);ctx.fillText(o.duration?`${T('建議時間：','Suggested time: ')}${o.duration} ${T('分鐘','minutes')}`:T('姓名：________________　　班別：________','Name: ____________________    Class: __________'),40,720);ctx.strokeStyle='#bdcbb4';ctx.beginPath();ctx.moveTo(40,757);ctx.lineTo(555,757);ctx.stroke();font(9);ctx.fillStyle='#7c8d75';ctx.fillText(T('題目保留原小冊子的數學式及圖像；題目旁編號為原冊索引。','Original mathematical notation and diagrams preserved. Source booklet IDs remain visible.'),40,784);}
 else{const {entries,options:o,index,total}=data;ctx.fillStyle='#185e50';ctx.fillRect(35,40,525,5);font(25,600);ctx.fillText(T('目錄','Contents'),35,93);font(10);ctx.fillStyle='#8a9a8b';ctx.fillText(`${o.mode==='teacher'?T('教師版','Teacher edition'):T('學生版','Student edition')} · ${T('按題目列可前往相應頁面','Click a question row to jump to its page')}`,35,118);font(10,600);ctx.fillText(T('題目','Question'),35,143);ctx.fillText(T('課題','Topic'),210,143);ctx.textAlign='right';ctx.fillText(T('分數','Marks'),508,143);ctx.fillText(T('頁','Page'),553,143);ctx.textAlign='left';entries.forEach((e,j)=>{const y=170+j*27;ctx.fillStyle=j%2?'#fff':'#f3f6f0';ctx.fillRect(35,y-18,525,27);font(10);ctx.fillText(`${String(index*22+j+1).padStart(2,'0')}  ${e.section} · ${e.year} ${T('第 ','Q')}${e.number}${T(' 題','')}`,42,y);font(language==='en'?8:10);wrap(ctx,e.topicName,210,y,246,12,1);ctx.textAlign='right';ctx.fillText(e.marks,508,y);ctx.fillStyle='#185e50';ctx.fillText(e.start,551,y);ctx.textAlign='left';});font(9);ctx.fillStyle='#83917d';ctx.fillText(`${T('目錄','Contents')} ${index+1} / ${total}`,35,794);}
 return Promise.resolve(Uint8Array.from(atob(c.toDataURL('image/png').split(',')[1]),c=>c.charCodeAt(0)));}
async function readAsset(path){if(!assetCache.has(path))assetCache.set(path,fetch(path).then(async r=>{if(!r.ok)throw Error(T('題目 PDF 無法讀取，請重試。','Unable to load question PDF. Please try again.'));return new Uint8Array(await r.arrayBuffer());}).catch(e=>{assetCache.delete(path);throw e;}));return assetCache.get(path);}
async function exportPdf(){if(busy||!selected.size)return;busy=true;renderSummary();$('exportStatus').classList.remove('error');$('exportPdf').innerHTML='<span>◌</span> 正在製作小冊子…';try{const result=await BankPDF.build({questions:chosen(),topics:bank.topics,options:options(),readAsset,renderSheet,onProgress:t=>$('exportStatus').textContent=translateText(t)});download(result.bytes,`${options().title.replace(/[\\/:*?"<>|]/g,'_')}_${options().mode==='student'?T('學生版','Student'):T('教師版','Teacher')}.pdf`);$('exportStatus').textContent=language==='en'?`Downloaded · ${result.questions} questions · ${result.pages} pages`:`已下載 · ${result.questions} 題 · ${result.pages} 頁`;toast('PDF 小冊子已製作完成');}catch(e){$('exportStatus').textContent=e.message||'製作失敗，請重試。';$('exportStatus').classList.add('error');}finally{busy=false;$('exportPdf').innerHTML='<span>↓</span> 下載 PDF 小冊子';renderSummary();}}
function saveRecipe(){download(JSON.stringify({type:'dse-topic-bank-selection',version:1,selected:[...selected],options:options()},null,2),'DSE_選題設定.json','application/json');toast('已儲存選題設定，可稍後重新載入');}
async function loadRecipe(file){try{const data=JSON.parse(await file.text());if(data.type!=='dse-topic-bank-selection'||!Array.isArray(data.selected))throw Error('請載入本系統儲存的選題設定。');const valid=new Set(bank.questions.map(q=>q.id));selected=new Set(data.selected.filter(id=>valid.has(id)));chosenTopics=new Set(chosen().map(q=>q.topic));setOptions(data.options);showSelected=true;page=0;render();toast(`已載入 ${selected.size} 題`);}catch(e){toast(e.message||'檔案無法讀取。');}finally{$('recipeFile').value='';}}
async function init(){try{let remembered;try{remembered=JSON.parse(localStorage.getItem(stateKey));}catch{}language=/[?&]lang=en\b/.test(globalThis.location?.search||'')?'en':(/[?&]lang=zh/.test(globalThis.location?.search||'')?'zh-Hant':remembered?.language==='en'?'en':'zh-Hant');$('language').value=language;const r=await fetch(language==='en'?'bank-en.json':'bank.json');if(!r.ok)throw Error('題庫資料無法讀取');bank=await r.json();banks.set(language,bank);$('bankCount').textContent=bank.questions.length;$('topicCount').textContent=`${bank.topics.length} 個分部課題 · A1 / A2 / B`;
 for(const id of ['yearFrom','yearTo'])$(id).innerHTML=Array.from({length:15},(_,i)=>`<option value="${2012+i}">${2012+i}</option>`).join('');$('yearFrom').value='2012';$('yearTo').value='2026';
 let restored=false;try{const s=JSON.parse(localStorage.getItem(stateKey));if(s){selected=new Set((s.selected||[]).filter(id=>bank.questions.some(q=>q.id===id)));chosenTopics=new Set((s.topics||[]).filter(id=>bank.topics.some(t=>t.id===id)));section=['A1','A2','B'].includes(s.section)?s.section:'A1';$('yearFrom').value=s.from||2012;$('yearTo').value=s.to||2026;setOptions(s.options);restored=true;}}catch{}if(!restored){chosenTopics.add(bank.topics[0].id);inTopics().forEach(q=>selected.add(q.id));}
 if(language==='en'&&$('bookletTitle').value==='數學課題練習')$('bookletTitle').value='Mathematics Topic Practice';$('language').onchange=()=>switchLanguage($('language').value);
 document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;renderTopics();persist();});$('topicList').onclick=e=>{const b=e.target.closest('[data-topic]');if(!b)return;const id=b.dataset.topic;if(chosenTopics.has(id)){chosenTopics.delete(id);bank.questions.filter(q=>q.topic===id).forEach(q=>selected.delete(q.id));}else{chosenTopics.add(id);bank.questions.filter(q=>q.topic===id&&yearMatch(q)).forEach(q=>selected.add(q.id));}showSelected=false;page=0;render();};
 for(const id of ['yearFrom','yearTo'])$(id).onchange=()=>{if(+$('yearFrom').value>+$('yearTo').value){$(id==='yearFrom'?'yearTo':'yearFrom').value=$(id).value;}selected=new Set(chosen().filter(yearMatch).map(q=>q.id));inTopics().forEach(q=>selected.add(q.id));page=0;render();};$('latest').onclick=()=>{$('yearFrom').value='2026';$('yearTo').value='2026';$('yearFrom').onchange();};
 $('questionList').onchange=e=>{const id=e.target.dataset.q;if(id){e.target.checked?selected.add(id):selected.delete(id);renderList();renderSummary();}};$('questionList').onclick=e=>{const b=e.target.closest('[data-preview]');if(b)preview(b.dataset.preview);};$('pagination').onclick=e=>{if(e.target.dataset.page){page+=e.target.dataset.page==='next'?1:-1;renderList();}};$('search').oninput=()=>{page=0;renderList();};$('selectVisible').onclick=()=>{filtered().forEach(q=>selected.add(q.id));renderList();renderSummary();toast('已加入全部結果');};$('clearTopics').onclick=()=>{chosenTopics.clear();selected.clear();showSelected=false;render();};$('clearSelection').onclick=()=>{selected.clear();renderList();renderSummary();};$('reviewSelection').onclick=()=>{showSelected=!showSelected;page=0;$('search').value='';renderList();renderSummary();};
 for(const id of ['bookletTitle','className','duration','mode','sort','extraSpace'])$(id).oninput=()=>{renderSummary();if(id==='sort')renderList();};$('exportPdf').onclick=exportPdf;$('saveRecipe').onclick=saveRecipe;$('loadRecipe').onclick=()=>$('recipeFile').click();$('recipeFile').onchange=e=>e.target.files[0]&&loadRecipe(e.target.files[0]);$('coverage').onclick=coverage;$('help').onclick=()=>language==='en'?englishHelp():modal('三步製作課題小冊子','<ol><li><b>選課題：</b>先選 A1、A2 或 B，再選課題和年份。按一下課題即可加入所有符合年份的題目，可跨分部選題。</li><li><b>挑題目：</b>取消不需要的題目，或開啟預覽。按「查看已選題目」檢查整份小冊子。</li><li><b>下載 PDF：</b>填寫名稱，選擇學生版或教師版，按下載即可取得封面、目錄及題目。</li></ol><p>選題會記在這個瀏覽器，也可儲存 JSON 選題設定以備下次使用。更改年份會重新加入已選課題中符合年份的題目。</p><p>PDF 首次生成需讀取原題目檔案；其後同一頁面會重用檔案。教師版會包含現有評卷參考，學生版不會包含解答。目錄可點擊跳頁，題目頁底部 CONTENTS 可返回目錄。</p>');render();}catch(e){$('questionList').innerHTML=`<p class="empty error">${esc(e.message)}<br>請重新整理頁面。</p>`;}}
const textPairs=[['課題練習 · 卷一','Topic Practice · Paper 1'],
['數學題庫','Math Bank'],['把課題，變成小冊子','Turn topics into booklets'],['。','.'],['選課題、挑題目、下載 PDF。你的下一份練習，從這裡開始。','Choose topics, select questions and download a PDF.'],['繁體中文題目','English questions'],['使用說明 ↗','How to use ↗'],['選擇課題','Choose topics'],['重設','Reset'],['年份範圍','Year range'],['只選 2026 年 →','2026 only →'],['按一下課題，加入該課題所有題目','Click a topic to add all matching questions'],['題目來自現有課題小冊子','Questions from existing topic booklets'],['原有數學式、圖像及評卷參考保留','Original notation, diagrams and marking retained'],['查看題庫涵蓋範圍 ↗','View bank coverage ↗'],['檢視題目','Review questions'],['選擇左側課題開始','Choose topics to begin'],['加入全部結果','Add all results'],['製作小冊子','Create booklet'],['即時更新','Live summary'],['數學課題練習','Mathematics Topic Practice'],['選擇課題以建立練習','Choose topics to build your booklet'],['學生版','Student edition'],['教師版','Teacher edition'],['已選題目','Selected'],['總分','Total marks'],['題目頁','Question pages'],['小冊子名稱','Booklet title'],['班別／對象','Class / audience'],['建議時間（分鐘）','Suggested time (minutes)'],['輸出版本','Edition'],['學生版 · 題目及作答空間','Student · Questions and working space'],['教師版 · 題目及評卷參考','Teacher · Questions and marking schemes'],['題目排列','Question order'],['按分部及課題 · 年份由舊至新','Section / topic · Oldest first'],['按分部及課題 · 2026 優先','Section / topic · Newest first'],['按年份由新至舊','Year · Newest first'],['每題加一頁作答紙','Add a working page per question'],['查看已選題目','Review selected questions'],['返回課題結果','Back to topic results'],['清空','Clear'],['下載 PDF 小冊子','Download PDF booklet'],['含封面、可點擊目錄及連續頁碼','Cover, clickable contents and continuous page numbers'],['儲存選題設定','Save selection'],['載入設定','Load selection'],['為教學而整理','Organised for teaching'],['繁體中文','English'],['題庫以現有小冊子收錄題目為準','Coverage follows the existing topic booklets'],['搜尋課題、年份或題號…','Search topics, years or question numbers…'],['例如：中五 A 班','e.g. Form 5A'],['選填','Optional'],['檢視題目 ↗','Preview question ↗'],['← 上一頁','← Previous'],['下一頁 →','Next →'],['尚未加入題目。','No questions selected yet.'],['此範圍沒有符合的題目。','No questions match this range.'],['試試其他年份或課題。','Try another year range or topic.'],['請選擇左側課題。','Choose a topic on the left.'],['按一下即可加入課題內的題目。','One click adds its matching questions.'],['預覽顯示題目的第一頁；PDF 輸出會包含整題及續頁。','Preview shows the first page. PDF export includes the complete question and continuation pages.'],['開啟原題目 PDF ↗','Open source question PDF ↗'],['開啟評卷參考 PDF ↗','Open marking scheme PDF ↗'],['已加入全部結果','All results added'],['PDF 小冊子已製作完成','PDF booklet ready'],['正在製作小冊子…','Creating booklet…'],['題庫資料無法讀取','Unable to load the question bank'],['請重新整理頁面。','Please refresh the page.'],['已儲存選題設定，可稍後重新載入','Selection saved. You can load it later.'],['請載入本系統儲存的選題設定。','Please choose a selection file saved by this app.'],['檔案無法讀取。','Unable to read this file.']
];
function englishCoverage(){modal('Question bank coverage',`<p><b>${bank.questions.length} English questions</b>, ${bank.topics.length} section-specific topics, 2012–2026. Coverage follows the existing topic booklets. A2 contains selected questions, not every question from every paper.</p><table><thead><tr><th>Year</th><th>A1</th><th>A2</th><th>B</th><th>Total</th></tr></thead><tbody>${Array.from({length:15},(_,i)=>2026-i).map(y=>{const n=['A1','A2','B'].map(s=>bank.questions.filter(q=>q.year===y&&q.section===s).length);return `<tr><td>${y}</td>${n.map(v=>`<td>${v}</td>`).join('')}<td>${n.reduce((a,b)=>a+b,0)}</td></tr>`;}).join('')}</tbody></table><p>The student edition includes questions and working pages. The teacher edition includes matched marking schemes. The original PDF mathematical notation and diagrams are preserved.</p>`);}
function englishHelp(){modal('Create a booklet in three steps','<ol><li><b>Choose topics:</b> Select A1, A2 or B and a year range. One click adds all matching questions. You may combine sections.</li><li><b>Review questions:</b> Preview questions or remove unwanted ones. Use Review selected questions to check the full selection.</li><li><b>Download PDF:</b> Enter a title and choose Student or Teacher. Your booklet includes a cover, clickable contents, complete questions and continuous page numbers.</li></ol><p>Switch the language selector to use the English or Traditional Chinese question bank. The same selected question IDs are retained when switching languages. Save selection exports a JSON settings file; Load selection restores it. Selections are also saved in this browser.</p><p>Changing the year range adds the matching questions from selected topics again. The first PDF export downloads source assets; later exports reuse them. CONTENTS links in the PDF return to the contents page.</p>');}
const originals=new WeakMap(),attrOriginals=new WeakMap();
function translateText(value){if(language!=='en')return String(value);let s=String(value);const trim=s.trim();const exact=textPairs.find(([a])=>a===trim);if(exact)return s.replace(trim,exact[1]);return s.replace(/(\d+) 個分部課題/g,'$1 section-specific topics').replace(/(\d+) 個已選課題/g,'$1 selected topics').replace(/(\d+) 年 · 第 (\d+) 題/g,'$1 · Q$2').replace(/(\d+) 年 · (A1|A2|B) 第 (\d+) 題/g,'$1 · $2 Q$3').replace(/(\d+) 題/g,'$1 questions').replace(/(\d+) 分/g,'$1 marks').replace('小冊子內的題目','Selected booklet questions').replace('正在儲存 PDF…','Saving PDF…').replace(/正在編排 (\d+) \/ (\d+) 題…/,'Arranging $1 / $2 questions…').replace(/正在編排 (\d+) \/ (\d+) questions…/,'Arranging $1 / $2 questions…').replace(/讀取 (A1|A2|B) 學生版 題目…/,'Loading $1 student questions…').replace(/讀取 (A1|A2|B) 教師版 題目…/,'Loading $1 teacher questions…').replace(/已載入 (\d+) questions/,'Loaded $1 questions');}
function applyI18n(){if(!document.body||!document.createTreeWalker)return;document.documentElement.lang=language;document.body.lang=language;document.title=language==='en'?'DSE Mathematics Question Bank':'DSE 數學課題題庫';const walk=document.createTreeWalker(document.body,4);let node;while(node=walk.nextNode()){if(['SCRIPT','STYLE'].includes(node.parentElement?.tagName)||node.parentElement?.closest('#language'))continue;if(!originals.has(node))originals.set(node,node.nodeValue);node.nodeValue=language==='en'?translateText(originals.get(node)):originals.get(node);}for(const e of document.querySelectorAll('[placeholder]')){if(!attrOriginals.has(e))attrOriginals.set(e,e.getAttribute('placeholder'));e.setAttribute('placeholder',language==='en'?translateText(attrOriginals.get(e)):attrOriginals.get(e));}}
async function switchLanguage(next){if(busy){$('language').value=language;toast(T('請待 PDF 製作完成再切換語言。','Please wait for the PDF to finish before changing language.'));return;}const before=language;$('language').disabled=true;try{if(!banks.has(next)){const r=await fetch(next==='en'?'bank-en.json':'bank.json');if(!r.ok)throw Error('Unable to load this language.');banks.set(next,await r.json());}language=next;bank=banks.get(next);selected=new Set([...selected].filter(id=>bank.questions.some(q=>q.id===id)));chosenTopics=new Set([...chosenTopics].filter(id=>bank.topics.some(t=>t.id===id)));if(['數學課題練習','Mathematics Topic Practice'].includes($('bookletTitle').value))$('bookletTitle').value=T('數學課題練習','Mathematics Topic Practice');$('bankCount').textContent=bank.questions.length;$('topicCount').textContent=`${bank.topics.length} 個分部課題 · A1 / A2 / B`;page=0;const url=new URL(location.href);url.searchParams.set('lang',language==='en'?'en':'zh');history.replaceState(null,'',url);render();toast(T('已切換繁體中文題庫','English question bank loaded'));}catch(e){language=before;$('language').value=before;toast(e.message);}finally{$('language').disabled=false;}}

$('closeModal').onclick=()=>$('modal').close();$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').close();};init();
